global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['localhost:5000'] # Remplacez 'localhost' par l'adresse IP de votre serveur si n√©cessaire